title: Yang YOU
logo: /assets/img/yang.jpg
description: MSc Student in Robotics, Cranfield University. <br>
目前在法国计算机及自动化研究院（Nancy）Larsen实习，曾在中科院自动化所（北京）从事深度强化学习实习。英国Cranfield大学与法国国立应用科学学院双学位。<br>
 y.you@cranfield.ac.uk

show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
